federal crimes
nin0chat/Rewrite pull request #2
Opened 2024-10-24 21:57 UTC by nin0-dev

switch to fastify, and auth

2024-10-24 23:03 UTC, wingio requested changes
I apologize

2024-10-24 23:03 UTC, wingio commented on src/common/auth.ts
> +        .rows[0] as User;
Newline below here can help with readability, should do one after each of the condition checks too

2024-10-24 23:03 UTC, wingio commented on src/common/auth.ts
> +    const auth = await compare(password, potentialUser.password);
Before doing this you should check if an account with the provided email exists and fail early

2024-10-24 23:03 UTC, wingio commented on src/common/email.ts
> +    if (process.env.NODE_ENV === "development" && !process.env.SMTP2GO_KEY) {
Should use the `prod` constant you defined

2024-10-24 23:03 UTC, wingio commented on src/common/error.ts
> +}
Newline after here

2024-10-24 23:03 UTC, wingio commented on src/common/error.ts
> +export enum ErrorCodes {
Should use the singular form ErrorCode

2024-10-24 23:03 UTC, wingio commented on src/common/error.ts
> +        }
You should only return `{ code, message}` once at the end instead of for each case

2024-10-24 23:03 UTC, wingio commented on src/common/ids.ts
> +export function generateID(): string {
This isn't a great Snowflake implementation but it works for now, ill PR a more functional one later

2024-10-24 23:03 UTC, wingio commented on src/common/moderate.ts
> +);
Newline after here

2024-10-24 23:03 UTC, wingio commented on src/rest/auth.ts
> +};
Guh use newlines

2024-10-24 23:03 UTC, wingio commented on src/rest/auth.ts
> +            const auth = await checkCredentials(body.email, body.password);
add a newline before and after the following `if` block

2024-10-24 23:03 UTC, wingio commented on src/rest/auth.ts
> +        async (req, res) => {
Newline before each comment

2024-10-24 23:03 UTC, wingio commented on src/rest/auth.ts
> +        async function handler(request, res) {
Same as above

2024-10-25 16:04 UTC, splatterxl requested changes, later dismissed

2024-10-25 16:04 UTC, splatterxl commented on .env.example
> +POSTGRES_URL="postgresql://USERNAME:PASSWORD@IP:PORT/DBNAME"
```suggestion
POSTGRES_URL="postgresql://postgres:postgres@localhost:5432/nin0chat"
```
provide sane defaults instead of placeholders

2024-10-25 16:04 UTC, splatterxl commented on package.json
> +        "tsx": "^4.19.1",
why tsx? typescript already transpiles it

2024-10-25 16:04 UTC, splatterxl commented on src/common/auth.ts
> +        return {
i would prefer throwing an error here, clearer for both internal stuff and it can be caught with try catch (and by fastify automatically with my func in `rest`)

2024-10-25 16:04 UTC, splatterxl commented on src/common/auth.ts
> +export async function addToken(userID: bigint): Promise<string> {
Should be a function `generateToken` with core logic and then if token is added many times another function `addToken`, otherwise just dump it in the endpoint

2024-10-25 16:04 UTC, splatterxl commented on src/common/captcha.ts
> +    const { success } = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
bring this to a constant

2024-10-25 16:04 UTC, splatterxl commented on src/common/captcha.ts
> +import { prod } from "./constants";
```suggestion
import { prod } from "./constants.js";
```

2024-10-25 16:04 UTC, splatterxl commented on src/common/constants.ts
> +export const prod = process.env.NODE_ENV !== "development";
its better to have this as something like `__IS_DEV__`, people like to use NODE_ENV=staging sometimes so its not always prod

2024-10-25 16:04 UTC, splatterxl commented on src/common/email.ts
> +    console.log(r);
```suggestion
```

2024-10-25 16:04 UTC, splatterxl commented on src/common/moderate.ts
> +// WARN: All entries in this array must be regexes. All regexes will have /gu applied to them — manually-specified flags will be ignored!
```suggestion
/**
	* @warning All entries in this array must be regexes. All regexes will have /gu applied to them — manually-specified flags will be ignored!
	*/
```

2024-10-25 16:04 UTC, splatterxl commented on src/common/types.ts
> +    email?: string;
if this is optional, there should also be a bot boolean in db i think – just for easier querying if it comes to it

2024-10-25 16:04 UTC, splatterxl commented on src/index.ts
> +const modules = readdirSync(`./${prod ? "dist" : "src"}/rest`);
horror - use `tsc --watch` and `nodemon` instead.

2024-10-25 16:04 UTC, splatterxl commented on src/rest/auth.ts
> +                        return sendError(
we need APIError and throwing. much better, returning in this is an anti-pattern because an error is thrown

2024-10-25 16:04 UTC, splatterxl commented on src/rest/auth.ts
> +            if (moderateMessage(body.username).newMessageContent !== body.username) {
change to a function `shouldModerate`

2024-10-25 16:04 UTC, splatterxl commented on src/rest/auth.ts
> +            if (process.env.NODE_ENV !== "development")
no need the sendEmail function already checks this

2024-10-25 16:17 UTC, nin0-dev commented on package.json
> +        "tsx": "^4.19.1",
tsx is ts-node but good

insaneeeee

2024-10-25 16:22 UTC, nin0-dev commented on package.json
> +        "tsx": "^4.19.1",
it removes the need for ts-node and nodemon

2024-10-25 16:57 UTC, PoolloverNathan requested changes
uncertain as to our current style rules (do we have a prettier? is it configured to run CI?), but found some flaws and converted some others' comments to suggestions

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/auth.ts
> +}> {
why not use a dependent type?
```suggestion
): Promise<{
    success: true;
    id: bigint;
} | {
    success: false;
    error: "invalidCredentials" | "invalidTOTP" | "accountNotActivated";
}> {
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/constants.ts
> +export const prod = process.env.NODE_ENV !== "development";
how does this look?
```suggestion
export const prod = process.env.__IS_DEV__ ? +process.env.__IS_DEV__ : process.env.NODE_ENV === "production";
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/email.ts
> +    if (process.env.NODE_ENV === "development" && !process.env.SMTP2GO_KEY) {
making @wingio's comment a suggestion
```suggestion
import { prod } from "./constants";

export async function sendEmail(
    to: string[],
    subject: string,
    template_id: string,
    template_data?: object,
    bcc?: string[]
) {
    console.log(`Sending email to ${to} with ${bcc} with template ${template_id}`);

    if (!prod && !process.env.SMTP2GO_KEY) {
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/email.ts
> +            accept: "application/json"
style: trailing comma on multiline objects for better diffs
```suggestion
            accept: "application/json",
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/email.ts
> +            template_data
style: trailing comma on multiline objects for better diffs
```suggestion
            template_data,
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/email.ts
> +    const r = await q.json();
when is this variable used?

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/error.ts
> +    PermissionError
style: trailing comma on multiline objects for better diffs
```suggestion
    PermissionError,
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/moderate.ts
> +    "ultrakill"
style: trailing comma on multiline objects for better diffs
```suggestion
    "ultrakill",
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/common/moderate.ts
> +// WARN: All entries in this array must be regexes. All regexes will have /gu applied to them — manually-specified flags will be ignored!
(that comment was mine) didn't know `@warning` existed, thanks! `WARN:` is nvim syntax for the same thing

2024-10-25 16:57 UTC, PoolloverNathan commented on src/index.ts
> +                    ignore: "pid,hostname"
style: trailing comma on multiline objects for better diffs
```suggestion
                    ignore: "pid,hostname",
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/index.ts
> +        production: false
style: trailing comma on multiline objects for better diffs
```suggestion
        production: false,
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/rest/auth.ts
> +            };
unnecessary binding
```suggestion
            return { token: await addToken(auth.id) };
```

2024-10-25 16:57 UTC, PoolloverNathan commented on src/rest/auth.ts
> +                        turnstileKey: { type: "string" }
style: trailing comma on multiline objects for better diffs
```suggestion
                        turnstileKey: { type: "string" },
```

2024-10-25 16:57 UTC, PoolloverNathan commented on tsconfig.json
> +        "strict": false /* Enable all strict type-checking options. */,
horror — if this causes errors, it's probably a skill issue
```suggestion
        "strict": true /* Enable all strict type-checking options. */,
```

2024-10-25 17:04 UTC, nin0-dev commented on tsconfig.json
> +        "strict": false /* Enable all strict type-checking options. */,
who cares

2024-10-25 17:04 UTC, nin0-dev commented on src/common/auth.ts
> +}> {
didnt know this was doable

2024-10-25 17:08 UTC, nin0-dev commented on src/common/captcha.ts
> +import { prod } from "./constants";
doesnt tsc fix this

2024-10-25 17:10 UTC, PoolloverNathan commented on tsconfig.json
> +        "strict": false /* Enable all strict type-checking options. */,
> who cares

it makes the generated code `"use strict"` for saner JS behavior once compiled, as well as requiring a `!` to cause potentially-unsafe notnull assertions rather than silently assuming the value as non-nullable.

2024-10-25 17:17 UTC, nin0-dev commented on src/common/types.ts
> +    email?: string;
added

2024-10-25 18:37 UTC, nin0-dev commented on src/index.ts
> +const modules = readdirSync(`./${prod ? "dist" : "src"}/rest`);
now irrelevant

2024-10-25 19:12 UTC, splatterxl commented on src/common/constants.ts
> +export const prod = process.env.NODE_ENV !== "development";
I would prefer renaming the constant itself

2024-10-25 19:44 UTC, nin0-dev commented on src/common/constants.ts
> +export const prod = process.env.NODE_ENV !== "development";
nathan insane

2024-10-25 19:56 UTC, PoolloverNathan commented on src/common/constants.ts
> +export const prod = process.env.NODE_ENV !== "development";
> I would prefer renaming the constant itself 

@splatterxl ohh, thought you meant the environment variable

2024-10-27 14:44 UTC, splatterxl approved these changes

2024-10-27 17:21 UTC, merged